import OneEdgeInstability.P1

set_option linter.style.header false

/-!
# P3: module-level presentation-distance consequence

This file formalizes the logically separate module-level presentation-distance
consequence in the accompanying preprint, on top of the completed P1 finite
graph/Hilbert-measure result.

The required additional bridge is that the cellular presentations for
`H₀(fₘ)` and `H₀(gₘ)` have the same incidence matrix and label cost at most one,
which bounds the path-metric `1`-presentation distance. Do not treat the P1
proof alone as a proof of this statement.
-/

set_option autoImplicit false

namespace OneEdgeInstability.P3

open scoped BigOperators ENNReal NNReal
open OneEdgeInstability.P1
open CategoryTheory

universe u

/-! ## Finite labeled presentations and their persistence modules

These are the narrow definitions needed for the presentation-distance result.
They follow Bjerkevik--Lesnick, Section 2.2: rows are homogeneous generators,
columns are homogeneous relations, and the represented persistence module is
the pointwise cokernel of the induced morphism between finite free modules. -/

/-- A finite presentation matrix with an `ℝⁿ` grade on every row and column.
The homogeneity condition is exactly the condition for the matrix to define a
morphism between graded free persistence modules. -/
structure LabeledPresentation (K : Type u) [Field K] (n : ℕ)
    (Row Column : Type) [Fintype Row] [Fintype Column] where
  matrix : Row → Column → K
  rowGrade : Row → RealGrade n
  columnGrade : Column → RealGrade n
  homogeneous : ∀ r c, matrix r c ≠ 0 →
    RealGrade.LE (rowGrade r) (columnGrade c)

namespace LabeledPresentation

variable {K : Type u} [Field K] {n : ℕ}
variable {Row Column : Type} [Fintype Row] [Fintype Column]

/-- The active part of the finite free module generated by the rows. -/
def rowSpace (P : LabeledPresentation K n Row Column) (x : RealGrade n) :
    Submodule K (Row → K) where
  carrier := {v | ∀ r, ¬ RealGrade.LE (P.rowGrade r) x → v r = 0}
  zero_mem' := by simp
  add_mem' := by
    intro u v hu hv r hr
    simp [hu r hr, hv r hr]
  smul_mem' := by
    intro a v hv r hr
    simp [hv r hr]

theorem rowSpace_mono (P : LabeledPresentation K n Row Column)
    {x y : RealGrade n} (hxy : RealGrade.LE x y) :
    P.rowSpace x ≤ P.rowSpace y := by
  intro v hv r hry
  apply hv r
  intro hrx
  exact hry (fun i ↦ (hrx i).trans (hxy i))

/-- A relation column as a vector in the active row space. -/
def activeColumn (P : LabeledPresentation K n Row Column)
    (x : RealGrade n) (c : Column)
    (hc : RealGrade.LE (P.columnGrade c) x) : P.rowSpace x :=
  ⟨fun r ↦ P.matrix r c, by
    intro r hr
    by_contra hne
    exact hr (fun i ↦ (P.homogeneous r c hne i).trans (hc i))⟩

/-- Span of the active relation columns. -/
def relationSpace (P : LabeledPresentation K n Row Column) (x : RealGrade n) :
    Submodule K (P.rowSpace x) :=
  Submodule.span K (Set.range fun c :
    {c : Column // RealGrade.LE (P.columnGrade c) x} ↦
      P.activeColumn x c.1 c.2)

/-- Inclusion of active generators along `x ≤ y`. -/
def rowInclusion (P : LabeledPresentation K n Row Column)
    {x y : RealGrade n} (hxy : RealGrade.LE x y) :
    P.rowSpace x →ₗ[K] P.rowSpace y :=
  Submodule.inclusion (P.rowSpace_mono hxy)

theorem rowInclusion_activeColumn
    (P : LabeledPresentation K n Row Column)
    {x y : RealGrade n} (hxy : RealGrade.LE x y)
    (c : Column) (hc : RealGrade.LE (P.columnGrade c) x) :
    P.rowInclusion hxy (P.activeColumn x c hc) =
      P.activeColumn y c (fun i ↦ (hc i).trans (hxy i)) := by
  rfl

theorem relationSpace_le_comap_rowInclusion
    (P : LabeledPresentation K n Row Column)
    {x y : RealGrade n} (hxy : RealGrade.LE x y) :
    P.relationSpace x ≤ (P.relationSpace y).comap (P.rowInclusion hxy) := by
  apply Submodule.span_le.2
  rintro z ⟨c, rfl⟩
  change P.rowInclusion hxy (P.activeColumn x c.1 c.2) ∈ P.relationSpace y
  rw [P.rowInclusion_activeColumn hxy c.1 c.2]
  exact Submodule.subset_span ⟨⟨c.1, fun i ↦ (c.2 i).trans (hxy i)⟩, rfl⟩

/-- The pointwise cokernel represented by `P`. -/
abbrev moduleAt (P : LabeledPresentation K n Row Column) (x : RealGrade n) :=
  P.rowSpace x ⧸ P.relationSpace x

/-- Structure map of the pointwise cokernels. -/
noncomputable def moduleMap (P : LabeledPresentation K n Row Column)
    {x y : RealGrade n} (hxy : RealGrade.LE x y) :
    P.moduleAt x →ₗ[K] P.moduleAt y :=
  (P.relationSpace x).mapQ (P.relationSpace y) (P.rowInclusion hxy)
    (P.relationSpace_le_comap_rowInclusion hxy)

end LabeledPresentation

/-- Objects and structure maps of an `ℝⁿ`-indexed linear diagram. -/
structure PersistenceModuleData (K : Type u) [Field K] (n : ℕ) where
  obj : RealGrade n → ModuleCat.{u} K
  mapLE : ∀ {x y : RealGrade n}, RealGrade.LE x y → (obj x ⟶ obj y)

/-- A concrete `ℝⁿ`-indexed persistence module, including its identity and
composition laws. -/
structure PersistenceModule (K : Type u) [Field K] (n : ℕ) where
  data : PersistenceModuleData K n
  map_id : ∀ (x : RealGrade n) (v : data.obj x),
    data.mapLE (x := x) (y := x) (fun _ ↦ le_rfl) v = v
  map_comp : ∀ {x y z : RealGrade n}
    (hxy : RealGrade.LE x y) (hyz : RealGrade.LE y z) (v : data.obj x),
    data.mapLE (x := y) (y := z) hyz
        (data.mapLE (x := x) (y := y) hxy v) =
      data.mapLE (x := x) (y := z) (fun i ↦ (hxy i).trans (hyz i)) v

abbrev PersistenceModule.obj {K : Type u} [Field K] {n : ℕ}
    (M : PersistenceModule K n) (x : RealGrade n) := M.data.obj x

abbrev PersistenceModule.mapLE {K : Type u} [Field K] {n : ℕ}
    (M : PersistenceModule K n) {x y : RealGrade n}
    (hxy : RealGrade.LE x y) : M.obj x ⟶ M.obj y := M.data.mapLE hxy

noncomputable def LabeledPresentation.toPersistenceModule
    {K : Type u} [Field K] {n : ℕ}
    {Row Column : Type} [Fintype Row] [Fintype Column]
    (P : LabeledPresentation K n Row Column) : PersistenceModule K n where
  data :=
    { obj := fun x ↦ ModuleCat.of K (P.moduleAt x)
      mapLE := fun hxy ↦ ModuleCat.ofHom (P.moduleMap hxy) }
  map_id x v := by
    refine Submodule.Quotient.induction_on (P.relationSpace x) v ?_
    intro v
    simp [LabeledPresentation.moduleMap, LabeledPresentation.rowInclusion]
    congr 1
  map_comp hxy hyz v := by
    refine Submodule.Quotient.induction_on (P.relationSpace _) v ?_
    intro v
    simp [LabeledPresentation.moduleMap, LabeledPresentation.rowInclusion]
    congr 1

/-- Natural linear isomorphism of the concrete persistence modules above. -/
structure PersistenceModuleIso {K : Type u} [Field K] {n : ℕ}
    (M N : PersistenceModule K n) where
  app : ∀ x, M.obj x ≃ₗ[K] N.obj x
  naturality : ∀ {x y : RealGrade n} (hxy : RealGrade.LE x y) (v : M.obj x),
    app y (M.mapLE hxy v) = N.mapLE hxy (app x v)

def LabeledPresentation.Presents
    {K : Type u} [Field K] {n : ℕ}
    {Row Column : Type} [Fintype Row] [Fintype Column]
    (P : LabeledPresentation K n Row Column) (M : PersistenceModule K n) : Prop :=
  Nonempty (PersistenceModuleIso P.toPersistenceModule M)

theorem LabeledPresentation.presents_toPersistenceModule
    {K : Type u} [Field K] {n : ℕ}
    {Row Column : Type} [Fintype Row] [Fintype Column]
    (P : LabeledPresentation K n Row Column) : P.Presents P.toPersistenceModule := by
  refine ⟨{ app := fun x ↦ LinearEquiv.refl K (P.moduleAt x)
            naturality := ?_ }⟩
  intro x y hxy v
  rfl

/-! ## The actual preliminary and path-metric presentation distances -/

/-- A finite presentation witness for a persistence module. -/
structure PresentationWitness {K : Type u} [Field K] {n : ℕ}
    (M : PersistenceModule K n) where
  Row : Type
  Column : Type
  [rowFintype : Fintype Row]
  [columnFintype : Fintype Column]
  presentation : LabeledPresentation K n Row Column
  presents : presentation.Presents M

/-- Finitely presented means admitting one of the finite cokernel
presentations above. -/
def FinitelyPresented {K : Type u} [Field K] {n : ℕ}
    (M : PersistenceModule K n) : Prop := Nonempty (PresentationWitness M)

theorem LabeledPresentation.finitelyPresented_toPersistenceModule
    {K : Type u} [Field K] {n : ℕ}
    {Row Column : Type} [Fintype Row] [Fintype Column]
    (P : LabeledPresentation K n Row Column) :
    FinitelyPresented P.toPersistenceModule :=
  ⟨{ Row := Row
     Column := Column
     presentation := P
     presents := P.presents_toPersistenceModule }⟩

/-- The `p=1` label distance between two presentations with the same row
and column indexing.  This is `‖L(P)-L(Q)‖₁` from the cited definition. -/
def presentationLabelL1 {K : Type u} [Field K] {n : ℕ}
    {Row Column : Type} [Fintype Row] [Fintype Column]
    (P Q : LabeledPresentation K n Row Column) : ℝ :=
  (∑ r, realL1Distance (P.rowGrade r) (Q.rowGrade r)) +
    ∑ c, realL1Distance (P.columnGrade c) (Q.columnGrade c)

theorem presentationLabelL1_nonnegative {K : Type u} [Field K] {n : ℕ}
    {Row Column : Type} [Fintype Row] [Fintype Column]
    (P Q : LabeledPresentation K n Row Column) :
    0 ≤ presentationLabelL1 P Q := by
  apply add_nonneg <;> apply Finset.sum_nonneg <;> intro i _ <;>
    exact Finset.sum_nonneg fun _ _ ↦ abs_nonneg _

/-- A pair occurring in the infimum defining the preliminary presentation
distance: presentations of `M,N` with the same underlying matrix. -/
structure CompatiblePresentationPair {K : Type u} [Field K] {n : ℕ}
    (M N : PersistenceModule K n) where
  Row : Type
  Column : Type
  [rowFintype : Fintype Row]
  [columnFintype : Fintype Column]
  left : LabeledPresentation K n Row Column
  right : LabeledPresentation K n Row Column
  sameMatrix : left.matrix = right.matrix
  leftPresents : left.Presents M
  rightPresents : right.Presents N

noncomputable def CompatiblePresentationPair.cost
    {K : Type u} [Field K] {n : ℕ} {M N : PersistenceModule K n}
    (P : CompatiblePresentationPair M N) : ℝ≥0∞ := by
  letI := P.rowFintype
  letI := P.columnFintype
  exact ENNReal.ofReal (presentationLabelL1 P.left P.right)

/-- Bjerkevik--Lesnick's preliminary distance `dHat_I^1`: the infimum of
label costs over compatible (same-matrix) finite presentations. -/
noncomputable def preliminaryPresentationDistance
    {K : Type u} [Field K] {n : ℕ}
    (M N : PersistenceModule K n) : ℝ≥0∞ :=
  sInf (Set.range fun P : CompatiblePresentationPair M N ↦ P.cost)

theorem preliminaryPresentationDistance_le_cost
    {K : Type u} [Field K] {n : ℕ} {M N : PersistenceModule K n}
    (P : CompatiblePresentationPair M N) :
    preliminaryPresentationDistance M N ≤ P.cost :=
  sInf_le ⟨P, rfl⟩

/-- A finite module path `Q₀,...,Qₗ`.  Each `cons` adds the first edge;
`nil` is the length-zero path. -/
inductive PresentationPath {K : Type u} [Field K] {n : ℕ} :
    PersistenceModule K n → PersistenceModule K n → Type (u + 1)
  | nil (M : PersistenceModule K n) : PresentationPath M M
  | cons (M N P : PersistenceModule K n) :
      PresentationPath N P → PresentationPath M P

noncomputable def PresentationPath.cost
    {K : Type u} [Field K] {n : ℕ}
    {M N : PersistenceModule K n} (path : PresentationPath M N) : ℝ≥0∞ :=
  match path with
  | .nil _ => 0
  | .cons M N _ tail => preliminaryPresentationDistance M N + tail.cost

noncomputable def directPresentationPath
    {K : Type u} [Field K] {n : ℕ}
    (M N : PersistenceModule K n) : PresentationPath M N :=
  .cons M N N (.nil N)

@[simp]
theorem directPresentationPath_cost
    {K : Type u} [Field K] {n : ℕ}
    (M N : PersistenceModule K n) :
    (directPresentationPath M N).cost = preliminaryPresentationDistance M N := by
  simp [directPresentationPath, PresentationPath.cost]

/-- Definition 3.2's path metric: the infimum of the sums of preliminary
presentation distances over all finite module paths. -/
noncomputable def presentationDistance1
    {K : Type u} [Field K] {n : ℕ}
    (M N : PersistenceModule K n) : ℝ≥0∞ :=
  sInf (Set.range fun path : PresentationPath M N ↦ path.cost)

theorem presentationDistance1_le_preliminary
    {K : Type u} [Field K] {n : ℕ}
    (M N : PersistenceModule K n) :
    presentationDistance1 M N ≤ preliminaryPresentationDistance M N := by
  apply sInf_le
  exact ⟨directPresentationPath M N, directPresentationPath_cost M N⟩

theorem presentationDistance1_le_compatible_cost
    {K : Type u} [Field K] {n : ℕ} {M N : PersistenceModule K n}
    (P : CompatiblePresentationPair M N) :
    presentationDistance1 M N ≤ P.cost :=
  (presentationDistance1_le_preliminary M N).trans
    (preliminaryPresentationDistance_le_cost P)

/-! ## The two cellular `H₀` presentations -/

/-- Oriented cellular incidence matrix of `Sₘ`: `e=s-t`, `aⱼ=s-uⱼ`,
and `bⱼ=uⱼ-t`. -/
def incidenceMatrix (K : Type u) [Field K] (m : ℕ) :
    Vertex m → Edge m → K
  | .s, .e => 1
  | .t, .e => -1
  | .u _, .e => 0
  | .s, .a _ => 1
  | .t, .a _ => 0
  | .u i, .a j => if i = j then -1 else 0
  | .s, .b _ => 0
  | .t, .b _ => -1
  | .u i, .b j => if i = j then 1 else 0

theorem incidenceMatrix_nonzero_mem_endpoints
    (K : Type u) [Field K] (m : ℕ) (v : Vertex m) (edge : Edge m)
    (h : incidenceMatrix K m v edge ≠ 0) : v ∈ endpoints edge := by
  cases edge <;> cases v <;> simp_all [incidenceMatrix, endpoints]

/-- Cellular degree-zero presentation of a monotone filtered graph.  At each
parameter its cokernel is `C₀ / im ∂₁`, so the resulting persistence module
is ordinary cellular `H₀` over `K`. -/
def cellularH0Presentation (K : Type u) [Field K] {m n : ℕ}
    (F : Simplex m → RealGrade n) (hF : RealMonotoneFiltration F) :
    LabeledPresentation K n (Vertex m) (Edge m) where
  matrix := incidenceMatrix K m
  rowGrade v := F (.vertex v)
  columnGrade edge := F (.edge edge)
  homogeneous v edge h := hF edge v
    (incidenceMatrix_nonzero_mem_endpoints K m v edge h)

/-! ### Pointwise bridge to the ordinary cellular `H₀` quotient -/

/-- When all vertices enter together and are active at `x`, the active row
space is the usual finite zero-chain space. -/
noncomputable def activeRowEquivFinsupp
    (K : Type u) [Field K] {m n : ℕ}
    (F : Simplex m → RealGrade n) (hF : RealMonotoneFiltration F)
    (hcommon : ∀ v, F (.vertex v) = F (.vertex (.s : Vertex m)))
    (x : RealGrade n) (hv : realVerticesActive F x) :
    (cellularH0Presentation K F hF).rowSpace x ≃ₗ[K] (Vertex m →₀ K) where
  toFun z := (Finsupp.linearEquivFunOnFinite K K (Vertex m)).symm z.1
  invFun z := ⟨Finsupp.linearEquivFunOnFinite K K (Vertex m) z, by
    intro v hnot
    exfalso
    apply hnot
    change RealGrade.LE (F (.vertex v)) x
    rw [hcommon v]
    exact hv⟩
  left_inv z := by
    apply Subtype.ext
    exact (Finsupp.linearEquivFunOnFinite K K (Vertex m)).apply_symm_apply z.1
  right_inv z :=
    (Finsupp.linearEquivFunOnFinite K K (Vertex m)).symm_apply_apply z
  map_add' _ _ := by simp
  map_smul' _ _ := by simp

/-- Under the zero-chain equivalence, every presentation column is its actual
oriented cellular edge boundary. -/
theorem activeRowEquivFinsupp_activeColumn
    (K : Type u) [Field K] {m n : ℕ}
    (F : Simplex m → RealGrade n) (hF : RealMonotoneFiltration F)
    (hcommon : ∀ v, F (.vertex v) = F (.vertex (.s : Vertex m)))
    (x : RealGrade n) (hv : realVerticesActive F x)
    (edge : Edge m) (hedge : RealGrade.LE (F (.edge edge)) x) :
    activeRowEquivFinsupp K F hF hcommon x hv
        ((cellularH0Presentation K F hF).activeColumn x edge hedge) =
      match edge with
      | .e => Finsupp.single .s 1 - Finsupp.single .t 1
      | .a j => Finsupp.single .s 1 - Finsupp.single (.u j) 1
      | .b j => Finsupp.single (.u j) 1 - Finsupp.single .t 1 := by
  ext v
  change incidenceMatrix K m v edge = _
  cases edge with
  | e => cases v <;> simp [incidenceMatrix]
  | a je =>
      cases v with
      | s => simp [incidenceMatrix]
      | t => simp [incidenceMatrix]
      | u j => by_cases h : j = je <;> simp [incidenceMatrix, h]
  | b je =>
      cases v with
      | s => simp [incidenceMatrix]
      | t => simp [incidenceMatrix]
      | u j => by_cases h : j = je <;> simp [incidenceMatrix, h]

/-- The span of the active presentation columns is exactly the cellular edge
boundary span of the real sublevel graph. -/
theorem activeRelationSpace_map_eq_cellularEdgeBoundarySpan
    (K : Type u) [Field K] {m n : ℕ}
    (F : Simplex m → RealGrade n) (hF : RealMonotoneFiltration F)
    (hcommon : ∀ v, F (.vertex v) = F (.vertex (.s : Vertex m)))
    (x : RealGrade n) (hv : realVerticesActive F x) :
    ((cellularH0Presentation K F hF).relationSpace x).map
        (activeRowEquivFinsupp K F hF hcommon x hv).toLinearMap =
      cellularEdgeBoundarySpan K (realSublevelGraph F x) := by
  let P := cellularH0Presentation K F hF
  let E := activeRowEquivFinsupp K F hF hcommon x hv
  apply le_antisymm
  · rw [Submodule.map_le_iff_le_comap]
    apply Submodule.span_le.2
    rintro z ⟨⟨edge, hedge⟩, rfl⟩
    change E (P.activeColumn x edge hedge) ∈
      cellularEdgeBoundarySpan K (realSublevelGraph F x)
    have hc : RealGrade.LE (F (.edge edge)) x := by
      simpa [P, cellularH0Presentation] using hedge
    cases edge with
    | e =>
        rw [show E (P.activeColumn x .e hedge) =
            Finsupp.single .s 1 - Finsupp.single .t 1 by
          convert activeRowEquivFinsupp_activeColumn
            K F hF hcommon x hv .e hc using 1]
        exact Submodule.subset_span ⟨.s, .t, by
          simpa [realSublevelGraph, realEdgeActive] using hc, rfl⟩
    | a j =>
        rw [show E (P.activeColumn x (.a j) hedge) =
            Finsupp.single .s 1 - Finsupp.single (.u j) 1 by
          convert activeRowEquivFinsupp_activeColumn
            K F hF hcommon x hv (.a j) hc using 1]
        exact Submodule.subset_span ⟨.s, .u j, by
          simpa [realSublevelGraph, realEdgeActive] using hc, rfl⟩
    | b j =>
        rw [show E (P.activeColumn x (.b j) hedge) =
            Finsupp.single (.u j) 1 - Finsupp.single .t 1 by
          convert activeRowEquivFinsupp_activeColumn
            K F hF hcommon x hv (.b j) hc using 1]
        exact Submodule.subset_span ⟨.u j, .t, by
          simpa [realSublevelGraph, realEdgeActive] using hc, rfl⟩
  · apply Submodule.span_le.2
    rintro z ⟨v, w, hadj, rfl⟩
    have hcolumn (edge : Edge m)
        (hedge : RealGrade.LE (F (.edge edge)) x) :
        E (P.activeColumn x edge hedge) ∈
          (P.relationSpace x).map E.toLinearMap := by
      apply Submodule.mem_map.2
      refine ⟨P.activeColumn x edge hedge, ?_, rfl⟩
      exact Submodule.subset_span ⟨⟨edge, hedge⟩, rfl⟩
    have hboundary (edge : Edge m)
        (hedge : RealGrade.LE (F (.edge edge)) x) :
        (match edge with
          | .e => Finsupp.single .s 1 - Finsupp.single .t 1
          | .a j => Finsupp.single .s 1 - Finsupp.single (.u j) 1
          | .b j => Finsupp.single (.u j) 1 - Finsupp.single .t 1) ∈
          (P.relationSpace x).map E.toLinearMap := by
      have h := hcolumn edge hedge
      rw [activeRowEquivFinsupp_activeColumn K F hF hcommon x hv edge hedge] at h
      exact h
    cases v with
    | s =>
        cases w with
        | s => simpa [realSublevelGraph] using hadj
        | t =>
            have hedge : RealGrade.LE (F (.edge (.e : Edge m))) x := by
              simpa [realSublevelGraph, realEdgeActive] using hadj
            exact hboundary .e hedge
        | u j =>
            have hedge : RealGrade.LE (F (.edge (.a j))) x := by
              simpa [realSublevelGraph, realEdgeActive] using hadj
            exact hboundary (.a j) hedge
    | t =>
        cases w with
        | s =>
            have hedge : RealGrade.LE (F (.edge (.e : Edge m))) x := by
              simpa [realSublevelGraph, realEdgeActive] using hadj
            change Finsupp.single .t 1 - Finsupp.single .s 1 ∈
              (P.relationSpace x).map E.toLinearMap
            simpa only [neg_sub] using
              ((P.relationSpace x).map E.toLinearMap).neg_mem (hboundary .e hedge)
        | t => simpa [realSublevelGraph] using hadj
        | u j =>
            have hedge : RealGrade.LE (F (.edge (.b j))) x := by
              simpa [realSublevelGraph, realEdgeActive] using hadj
            change Finsupp.single .t 1 - Finsupp.single (.u j) 1 ∈
              (P.relationSpace x).map E.toLinearMap
            simpa only [neg_sub] using
              ((P.relationSpace x).map E.toLinearMap).neg_mem (hboundary (.b j) hedge)
    | u i =>
        cases w with
        | s =>
            have hedge : RealGrade.LE (F (.edge (.a i))) x := by
              simpa [realSublevelGraph, realEdgeActive] using hadj
            change Finsupp.single (.u i) 1 - Finsupp.single .s 1 ∈
              (P.relationSpace x).map E.toLinearMap
            simpa only [neg_sub] using
              ((P.relationSpace x).map E.toLinearMap).neg_mem (hboundary (.a i) hedge)
        | t =>
            have hedge : RealGrade.LE (F (.edge (.b i))) x := by
              simpa [realSublevelGraph, realEdgeActive] using hadj
            exact hboundary (.b i) hedge
        | u j => simpa [realSublevelGraph] using hadj

/-- At an active parameter, the presented pointwise cokernel is linearly
equivalent to the cellular zero-chain quotient used in P1. -/
noncomputable def activeModuleAtEquivCellularGraphH0
    (K : Type u) [Field K] {m n : ℕ}
    (F : Simplex m → RealGrade n) (hF : RealMonotoneFiltration F)
    (hcommon : ∀ v, F (.vertex v) = F (.vertex (.s : Vertex m)))
    (x : RealGrade n) (hv : realVerticesActive F x) :
    (cellularH0Presentation K F hF).moduleAt x ≃ₗ[K]
      CellularGraphH0 K (realSublevelGraph F x) :=
  Submodule.Quotient.equiv
    ((cellularH0Presentation K F hF).relationSpace x)
    (cellularEdgeBoundarySpan K (realSublevelGraph F x))
    (activeRowEquivFinsupp K F hF hcommon x hv)
    (activeRelationSpace_map_eq_cellularEdgeBoundarySpan
      K F hF hcommon x hv)

/-- For a filtered graph whose vertices all enter together, the pointwise
finrank of its labeled cellular presentation is exactly the ordinary-`H₀`
component-count Hilbert function used in P1. -/
theorem cellularH0Presentation_finrank_eq_realOrdinaryH0Dim
    (K : Type u) [Field K] {m n : ℕ}
    (F : Simplex m → RealGrade n) (hF : RealMonotoneFiltration F)
    (hcommon : ∀ v, F (.vertex v) = F (.vertex (.s : Vertex m)))
    (x : RealGrade n) :
    Module.finrank K ((cellularH0Presentation K F hF).moduleAt x) =
      realOrdinaryH0Dim F x := by
  classical
  by_cases hv : realVerticesActive F x
  · calc
      Module.finrank K ((cellularH0Presentation K F hF).moduleAt x) =
          Module.finrank K (CellularGraphH0 K (realSublevelGraph F x)) :=
        (activeModuleAtEquivCellularGraphH0 K F hF hcommon x hv).finrank_eq
      _ = Nat.card (realSublevelGraph F x).ConnectedComponent :=
        finrank_cellularGraphH0 K (realSublevelGraph F x)
      _ = realOrdinaryH0Dim F x := by
        rw [realOrdinaryH0Dim, if_pos hv]
  · have hrow : (cellularH0Presentation K F hF).rowSpace x = ⊥ := by
      apply bot_unique
      intro z hz
      rw [Submodule.mem_bot]
      funext v
      apply hz v
      intro hvgrade
      apply hv
      change RealGrade.LE (F (.vertex (.s : Vertex m))) x
      rw [← hcommon v]
      exact hvgrade
    rw [realOrdinaryH0Dim, if_neg hv]
    have hle :
        Module.finrank K ((cellularH0Presentation K F hF).moduleAt x) ≤ 0 := by
      calc
        Module.finrank K ((cellularH0Presentation K F hF).moduleAt x) ≤
            Module.finrank K ((cellularH0Presentation K F hF).rowSpace x) :=
          Submodule.finrank_quotient_le _
        _ = 0 := by rw [hrow]; simp
    omega

def p3FFiltration (m k : ℕ) : Simplex m → RealGrade (3 + k) :=
  realifyFiltration (fGradePadded m k)

def p3GFiltration (m k : ℕ) : Simplex m → RealGrade (3 + k) :=
  realifyFiltration (gGradePadded m k)

theorem p3FFiltration_monotone (m k : ℕ) :
    RealMonotoneFiltration (p3FFiltration m k) :=
  realifyFiltration_monotone (fGradePadded_monotone m k)

theorem p3GFiltration_monotone (m k : ℕ) :
    RealMonotoneFiltration (p3GFiltration m k) :=
  realifyFiltration_monotone (gGradePadded_monotone m k)

theorem p3FFiltration_vertexGrade_eq (m k : ℕ) (v : Vertex m) :
    p3FFiltration m k (.vertex v) =
      p3FFiltration m k (.vertex (.s : Vertex m)) := rfl

theorem p3GFiltration_vertexGrade_eq (m k : ℕ) (v : Vertex m) :
    p3GFiltration m k (.vertex v) =
      p3GFiltration m k (.vertex (.s : Vertex m)) := rfl

def p3FPresentation (K : Type u) [Field K] (m k : ℕ) :
    LabeledPresentation K (3 + k) (Vertex m) (Edge m) :=
  cellularH0Presentation K (p3FFiltration m k) (p3FFiltration_monotone m k)

def p3GPresentation (K : Type u) [Field K] (m k : ℕ) :
    LabeledPresentation K (3 + k) (Vertex m) (Edge m) :=
  cellularH0Presentation K (p3GFiltration m k) (p3GFiltration_monotone m k)

/-- The two finitely presented ordinary-`H₀` persistence modules. -/
noncomputable def p3FModule (K : Type u) [Field K] (m k : ℕ) :
    PersistenceModule K (3 + k) := (p3FPresentation K m k).toPersistenceModule

noncomputable def p3GModule (K : Type u) [Field K] (m k : ℕ) :
    PersistenceModule K (3 + k) := (p3GPresentation K m k).toPersistenceModule

/-- The pointwise dimension of the presented `fₘ` module is exactly the P1
ordinary-`H₀` Hilbert function. -/
theorem p3FModule_finrank_eq_realOrdinaryH0Dim
    (K : Type u) [Field K] (m k : ℕ) (x : RealGrade (3 + k)) :
    Module.finrank K ((p3FModule K m k).obj x) =
      realOrdinaryH0Dim (p3FFiltration m k) x := by
  change Module.finrank K ((p3FPresentation K m k).moduleAt x) = _
  exact cellularH0Presentation_finrank_eq_realOrdinaryH0Dim
    K (p3FFiltration m k) (p3FFiltration_monotone m k)
      (p3FFiltration_vertexGrade_eq m k) x

/-- The pointwise dimension of the presented `gₘ` module is exactly the P1
ordinary-`H₀` Hilbert function. -/
theorem p3GModule_finrank_eq_realOrdinaryH0Dim
    (K : Type u) [Field K] (m k : ℕ) (x : RealGrade (3 + k)) :
    Module.finrank K ((p3GModule K m k).obj x) =
      realOrdinaryH0Dim (p3GFiltration m k) x := by
  change Module.finrank K ((p3GPresentation K m k).moduleAt x) = _
  exact cellularH0Presentation_finrank_eq_realOrdinaryH0Dim
    K (p3GFiltration m k) (p3GFiltration_monotone m k)
      (p3GFiltration_vertexGrade_eq m k) x

theorem p3FModule_finitelyPresented (K : Type u) [Field K] (m k : ℕ) :
    FinitelyPresented (p3FModule K m k) :=
  (p3FPresentation K m k).finitelyPresented_toPersistenceModule

theorem p3GModule_finitelyPresented (K : Type u) [Field K] (m k : ℕ) :
    FinitelyPresented (p3GModule K m k) :=
  (p3GPresentation K m k).finitelyPresented_toPersistenceModule

/-- The underlying incidence matrices agree entry-for-entry. -/
theorem p3_presentations_same_incidence_matrix
    (K : Type u) [Field K] (m k : ℕ) :
    (p3FPresentation K m k).matrix = (p3GPresentation K m k).matrix := rfl

/-- All row (generator) labels agree. -/
theorem p3_presentations_rowLabels_agree
    (K : Type u) [Field K] (m k : ℕ) (v : Vertex m) :
    (p3FPresentation K m k).rowGrade v =
      (p3GPresentation K m k).rowGrade v := rfl

/-- Every relation-column label except the central edge label agrees. -/
theorem p3_presentations_columnLabels_agree_of_ne_e
    (K : Type u) [Field K] (m k : ℕ) (edge : Edge m) (he : edge ≠ .e) :
    (p3FPresentation K m k).columnGrade edge =
      (p3GPresentation K m k).columnGrade edge := by
  cases edge with
  | e => exact (he rfl).elim
  | a j => rfl
  | b j => rfl

/-- The exceptional central relation label moves by exactly one in `ℓ¹`. -/
theorem p3_presentations_centralColumn_distance
    (K : Type u) [Field K] (m k : ℕ) :
    realL1Distance
      ((p3FPresentation K m k).columnGrade .e)
      ((p3GPresentation K m k).columnGrade .e) = 1 := by
  change realL1Distance
    ((Grade.zeroPad (k := k) (fGrade m (.edge .e))).toReal)
    ((Grade.zeroPad (k := k) (gGrade m (.edge .e))).toReal) = 1
  rw [realL1Distance_toReal, l1Distance_zeroPad]
  norm_num [fGrade, gGrade, l1Distance, Fin.sum_univ_succ]

/-- Hence the full same-matrix `p=1` presentation-label cost is one. -/
theorem p3_presentations_labelCost_eq_one
    (K : Type u) [Field K] (m k : ℕ) :
    presentationLabelL1 (p3FPresentation K m k) (p3GPresentation K m k) = 1 := by
  classical
  rw [presentationLabelL1]
  have hrows :
      (∑ v : Vertex m, realL1Distance
        ((p3FPresentation K m k).rowGrade v)
        ((p3GPresentation K m k).rowGrade v)) = 0 := by
    apply Finset.sum_eq_zero
    intro v _
    rw [p3_presentations_rowLabels_agree]
    exact realL1Distance_self _
  rw [hrows, zero_add, Finset.sum_eq_single (.e : Edge m)]
  · exact p3_presentations_centralColumn_distance K m k
  · intro edge _ he
    rw [p3_presentations_columnLabels_agree_of_ne_e K m k edge he]
    exact realL1Distance_self _
  · simp

noncomputable def p3CompatiblePresentationPair
    (K : Type u) [Field K] (m k : ℕ) :
    CompatiblePresentationPair (p3FModule K m k) (p3GModule K m k) where
  Row := Vertex m
  Column := Edge m
  left := p3FPresentation K m k
  right := p3GPresentation K m k
  sameMatrix := p3_presentations_same_incidence_matrix K m k
  leftPresents := (p3FPresentation K m k).presents_toPersistenceModule
  rightPresents := (p3GPresentation K m k).presents_toPersistenceModule

theorem p3CompatiblePresentationPair_cost
    (K : Type u) [Field K] (m k : ℕ) :
    (p3CompatiblePresentationPair K m k).cost = 1 := by
  rw [CompatiblePresentationPair.cost]
  change ENNReal.ofReal
    (presentationLabelL1 (p3FPresentation K m k) (p3GPresentation K m k)) = 1
  rw [p3_presentations_labelCost_eq_one]
  norm_num

/-- The direct compatible presentations bound the preliminary distance. -/
theorem p3_preliminaryPresentationDistance_le_one
    (K : Type u) [Field K] (m k : ℕ) :
    preliminaryPresentationDistance (p3FModule K m k) (p3GModule K m k) ≤ 1 := by
  calc
    preliminaryPresentationDistance (p3FModule K m k) (p3GModule K m k) ≤
        (p3CompatiblePresentationPair K m k).cost :=
      preliminaryPresentationDistance_le_cost (p3CompatiblePresentationPair K m k)
    _ = 1 := p3CompatiblePresentationPair_cost K m k

/-- The actual path-metric `1`-presentation distance satisfies `d_I^1 ≤ 1`. -/
theorem p3_presentationDistance1_le_one
    (K : Type u) [Field K] (m k : ℕ) :
    presentationDistance1 (p3FModule K m k) (p3GModule K m k) ≤ 1 :=
  (presentationDistance1_le_preliminary _ _).trans
    (p3_preliminaryPresentationDistance_le_one K m k)

/-! ## The Hilbert signed measure and the P3 consequence -/

/-- A transparent certificate that two labeled matrices are the two cellular
`H₀` presentations above and differ only by the unit move of the central
relation column.  In particular, this records the incidence matrix itself,
not just an abstract same-matrix witness. -/
def IsCentralColumnUnitMove {K : Type u} [Field K] {n m : ℕ}
    (P Q : LabeledPresentation K n (Vertex m) (Edge m)) : Prop :=
  P.matrix = incidenceMatrix K m ∧
  Q.matrix = incidenceMatrix K m ∧
  (∀ v, P.rowGrade v = Q.rowGrade v) ∧
  (∀ edge, edge ≠ (.e : Edge m) → P.columnGrade edge = Q.columnGrade edge) ∧
  realL1Distance (P.columnGrade .e) (Q.columnGrade .e) = 1 ∧
  presentationLabelL1 P Q = 1

theorem p3_presentations_isCentralColumnUnitMove
    (K : Type u) [Field K] (m k : ℕ) :
    IsCentralColumnUnitMove (p3FPresentation K m k)
      (p3GPresentation K m k) := by
  exact ⟨rfl, rfl, p3_presentations_rowLabels_agree K m k,
    p3_presentations_columnLabels_agree_of_ne_e K m k,
    p3_presentations_centralColumn_distance K m k,
    p3_presentations_labelCost_eq_one K m k⟩

/-- The bridge tying a same-graph presentation pair to the ordinary-`H₀`
Hilbert signed measure.  Besides identifying the cellular cokernel
presentations, it explicitly equates the pointwise module finranks with the
component-count Hilbert functions whose signed measures occur in the final
`IsOrdinaryH0HilbertKRPair` conjunct. -/
def IsOrdinaryH0HilbertPresentationPair
    (K : Type u) [Field K] {m n : ℕ} {I : Type} [Fintype I]
    (F G : Simplex m → RealGrade n)
    (P Q : LabeledPresentation K n (Vertex m) (Edge m))
    (M N : PersistenceModule K n)
    (muF muG mu : AtomicSignedMeasure n)
    (source target : I → RealGrade n) : Prop :=
  ∃ (hF : RealMonotoneFiltration F) (hG : RealMonotoneFiltration G),
    P = cellularH0Presentation K F hF ∧
    Q = cellularH0Presentation K G hG ∧
    P.Presents M ∧
    Q.Presents N ∧
    (∀ x, Module.finrank K (M.obj x) = realOrdinaryH0Dim F x) ∧
    (∀ x, Module.finrank K (N.obj x) = realOrdinaryH0Dim G x) ∧
    IsOrdinaryH0HilbertKRPair F G muF muG mu source target

/-- The finite primal `KR₁` cost between the actual Jordan parts, regarded as
an extended nonnegative real so it can be compared with the presentation path
metric.  Under `IsOrdinaryH0HilbertPresentationPair`, P1 proves that these
unit-atom measures are precisely the positive and negative Jordan parts of the
Hilbert signed-measure difference. -/
noncomputable def hilbertSignedWasserstein1 {n : ℕ} {I : Type} [Fintype I]
    (source target : I → RealGrade n) : ℝ≥0∞ :=
  measureKR1 (unitAtomMeasure source) (unitAtomMeasure target)

theorem p3_hilbertSignedWasserstein1_eq
    (m k : ℕ) (hm : 1 ≤ m) :
    hilbertSignedWasserstein1 (counterexampleSourcePointPadded m k)
      (counterexampleTargetPointPadded m k) = (2 * m : ℕ) := by
  rw [hilbertSignedWasserstein1,
    measureKR1_eq_card_of_separated_unit_matching
      (counterexampleSourcePointPadded m k)
      (counterexampleTargetPointPadded m k)
      (one_le_counterexamplePadded_source_target_distance hm k)
      (counterexamplePadded_corresponding_distance m k),
    card_counterexampleAtomIndex hm]

/-- The complete module-level family from the accompanying preprint.
The presentations are cellular ordinary-`H₀` presentations of the same real
filtered graph used in P1; their exact label cost is one, hence the actual
Bjerkevik--Lesnick path metric is at most one, while the Hilbert signed
Wasserstein distance is exactly `2m`. -/
theorem p3_H0_presentation_counterexample_family
    (K : Type u) [Field K] (n m : ℕ) (hn : 3 ≤ n) (hm : 1 ≤ m) :
    ∃ (F G : Simplex m → RealGrade n)
      (P Q : LabeledPresentation K n (Vertex m) (Edge m))
      (M N : PersistenceModule K n)
      (muF muG mu : AtomicSignedMeasure n)
      (source target : CounterexampleAtomIndex m → RealGrade n),
      FinitelyPresented M ∧
      FinitelyPresented N ∧
      IsOrdinaryH0HilbertPresentationPair K F G P Q M N
        muF muG mu source target ∧
      IsCentralColumnUnitMove P Q ∧
      realFiltrationL1Distance F G = 1 ∧
      presentationDistance1 M N ≤ 1 ∧
      hilbertSignedWasserstein1 source target = (2 * m : ℕ) := by
  obtain ⟨k, rfl : n = 3 + k⟩ := Nat.exists_eq_add_of_le hn
  refine ⟨p3FFiltration m k, p3GFiltration m k,
    p3FPresentation K m k, p3GPresentation K m k,
    p3FModule K m k, p3GModule K m k,
    h0FMeasurePadded m k, h0GMeasurePadded m k,
    hilbertDifferenceMeasurePadded m k,
    counterexampleSourcePointPadded m k,
    counterexampleTargetPointPadded m k,
    p3FModule_finitelyPresented K m k,
    p3GModule_finitelyPresented K m k, ?_,
    p3_presentations_isCentralColumnUnitMove K m k, ?_,
    p3_presentationDistance1_le_one K m k,
    p3_hilbertSignedWasserstein1_eq m k hm⟩
  · refine ⟨p3FFiltration_monotone m k, p3GFiltration_monotone m k,
      rfl, rfl, ?_, ?_, ?_, ?_,
      counterexamplePadded_isOrdinaryH0HilbertKRPair m k hm⟩
    · exact (p3FPresentation K m k).presents_toPersistenceModule
    · exact (p3GPresentation K m k).presents_toPersistenceModule
    · exact p3FModule_finrank_eq_realOrdinaryH0Dim K m k
    · exact p3GModule_finrank_eq_realOrdinaryH0Dim K m k
  · rw [p3FFiltration, p3GFiltration, realFiltrationL1Distance_realify,
      filtrationL1Distance_fGradePadded_gGradePadded]
    norm_num

/-- A proposed finite dimension-only P3 constant, restricted to finite graph
`H₀` modules.  Any universal P3 constant for finitely presented persistence
modules implies this restriction. -/
def OrdinaryH0HilbertPresentationBound
    (K : Type u) [Field K] (n : ℕ) (C : ℝ≥0) : Prop :=
  ∀ (m : ℕ) (I : Type) [Fintype I]
    (F G : Simplex m → RealGrade n)
    (P Q : LabeledPresentation K n (Vertex m) (Edge m))
    (M N : PersistenceModule K n)
    (muF muG mu : AtomicSignedMeasure n)
    (source target : I → RealGrade n),
    IsOrdinaryH0HilbertPresentationPair K F G P Q M N
      muF muG mu source target →
    hilbertSignedWasserstein1 source target ≤
      (C : ℝ≥0∞) * presentationDistance1 M N

/-- Quantitative P3 failure: in each fixed `n ≥ 3`, every finite proposed
constant is exceeded by members of the cellular ordinary-`H₀` family. -/
theorem p3_counterexample_family_unbounded
    (K : Type u) [Field K] (n : ℕ) (hn : 3 ≤ n) (C : ℝ≥0) :
    ∃ (m : ℕ) (F G : Simplex m → RealGrade n)
      (P Q : LabeledPresentation K n (Vertex m) (Edge m))
      (M N : PersistenceModule K n)
      (muF muG mu : AtomicSignedMeasure n)
      (source target : CounterexampleAtomIndex m → RealGrade n),
      1 ≤ m ∧
      FinitelyPresented M ∧
      FinitelyPresented N ∧
      IsOrdinaryH0HilbertPresentationPair K F G P Q M N
        muF muG mu source target ∧
      IsCentralColumnUnitMove P Q ∧
      presentationDistance1 M N ≤ 1 ∧
      hilbertSignedWasserstein1 source target = (2 * m : ℕ) ∧
      hilbertSignedWasserstein1 source target >
        (C : ℝ≥0∞) * presentationDistance1 M N := by
  obtain ⟨k, rfl : n = 3 + k⟩ := Nat.exists_eq_add_of_le hn
  obtain ⟨m, hmgt⟩ := exists_nat_gt (C : ℝ)
  have hmreal : (0 : ℝ) < m := lt_of_le_of_lt C.property hmgt
  have hmpos : 0 < m := by exact_mod_cast hmreal
  have hm : 1 ≤ m := Nat.one_le_iff_ne_zero.mpr (Nat.ne_of_gt hmpos)
  refine ⟨m, p3FFiltration m k, p3GFiltration m k,
    p3FPresentation K m k, p3GPresentation K m k,
    p3FModule K m k, p3GModule K m k,
    h0FMeasurePadded m k, h0GMeasurePadded m k,
    hilbertDifferenceMeasurePadded m k,
    counterexampleSourcePointPadded m k,
    counterexampleTargetPointPadded m k,
    hm, p3FModule_finitelyPresented K m k,
    p3GModule_finitelyPresented K m k, ?_,
    p3_presentations_isCentralColumnUnitMove K m k,
    p3_presentationDistance1_le_one K m k,
    p3_hilbertSignedWasserstein1_eq m k hm, ?_⟩
  · refine ⟨p3FFiltration_monotone m k, p3GFiltration_monotone m k,
      rfl, rfl, ?_, ?_, ?_, ?_,
      counterexamplePadded_isOrdinaryH0HilbertKRPair m k hm⟩
    · exact (p3FPresentation K m k).presents_toPersistenceModule
    · exact (p3GPresentation K m k).presents_toPersistenceModule
    · exact p3FModule_finrank_eq_realOrdinaryH0Dim K m k
    · exact p3GModule_finrank_eq_realOrdinaryH0Dim K m k
  · rw [p3_hilbertSignedWasserstein1_eq m k hm]
    have hmul :
        (C : ℝ≥0∞) * presentationDistance1
            (p3FModule K m k) (p3GModule K m k) ≤ (C : ℝ≥0∞) := by
      calc
        (C : ℝ≥0∞) * presentationDistance1
            (p3FModule K m k) (p3GModule K m k) ≤ (C : ℝ≥0∞) * 1 := by
          gcongr
          exact p3_presentationDistance1_le_one K m k
        _ = (C : ℝ≥0∞) := mul_one _
    have hCnat : (C : ℝ≥0∞) < (m : ℕ) := by
      exact_mod_cast hmgt
    have hmTwo : (m : ℝ≥0∞) ≤ (2 * m : ℕ) := by
      exact_mod_cast Nat.le_mul_of_pos_left m (by omega : 0 < 2)
    exact hmul.trans_lt (hCnat.trans_le hmTwo)

/-- P3: no finite Hilbert signed-Wasserstein stability constant depending only
on a fixed dimension `n ≥ 3` exists, already for the finite ordinary-`H₀`
cellular graph modules above. -/
theorem no_finite_dimension_only_P3_constant
    (K : Type u) [Field K] (n : ℕ) (hn : 3 ≤ n) :
    ¬ ∃ C : ℝ≥0, OrdinaryH0HilbertPresentationBound K n C := by
  rintro ⟨C, hbound⟩
  obtain ⟨m, F, G, P, Q, M, N, muF, muG, mu, source, target,
      _, _, _, hpair, _, _, _, hgt⟩ :=
    p3_counterexample_family_unbounded K n hn C
  exact (not_lt_of_ge
    (hbound m (CounterexampleAtomIndex m) F G P Q M N
      muF muG mu source target hpair)) hgt

end OneEdgeInstability.P3
